# Generated by Django 4.2.20 on 2025-05-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.SlugField(error_messages={'invalid': "ユーザ名は英数字と'_'(アンダーバー)が使えます"}, max_length=15, unique=True, verbose_name='ユーザー名'),
        ),
    ]
