# Generated by Django 4.2.20 on 2025-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.SlugField(max_length=15, unique=True, verbose_name='ユーザー名'),
        ),
    ]
