# Generated by Django 4.2.21 on 2025-05-25 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(error_messages={'blank': '名前を入力してください'}, max_length=50, verbose_name='ハンドルネーム')),
                ('bio', models.TextField(blank=True, max_length=160, verbose_name='自己紹介')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='プロフィール画像')),
                ('place', models.CharField(blank=True, max_length=30, verbose_name='場所')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='ウェブサイト')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
