# Generated by Django 4.2.21 on 2025-05-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(blank=True, max_length=50, verbose_name='ハンドルネーム'),
        ),
    ]
