services:
  db:
    image: postgres:alpine3.18
    container_name: "db_myapp"
    expose:
      - "5432"
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../db/database:/var/lib/postgresql/data
  djangoapp:
    image: django/cyclehood:latest
    build: ./djangoapp
    container_name: "djangoapp_myapp"
    ports:
      - 8080:8080
    environment:
      - DEBUG=1
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspaces/myapp
  frontend:
    image: node:20
    container_name: "frontend_myapp"
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - djangoapp
