# Generated by Django 4.2.21 on 2025-06-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='posted_date',
        ),
    ]
